### ISSUE TITLE
Ressources github

### ISSUE THREAD

**Issue by Rubeekub** [LadyKerr/github-certification-guide#5]

**Comment by LadyKerr** [comment]
Hi @Rubeekub do you have a question?

**Comment by Rubeekub** [comment]
hi,
sorry i m novice, i was just trying to save your informations, don t want
to disturb you.
Thanks you for sharing!
have a nice day,
and i wish you an happy new year!

Le mer. 10 janv. 2024 à 15:39, Kedasha Kerr ***@***.***> a
écrit :
